---
- name: Download package
  become: yes
  get_url:
    url: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
    dest: /tmp
- name: Install package
  become: yes
  command: "dpkg -i /tmp/zabbix-release_5.0-1+focal_all.deb"
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
- name: Install initial composants
  apt:
    name: ['zabbix-agent2']
    state: present
- name: replace local name
  lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: 'Hostname=Zabbix server'
    line: 'Hostname={{ansible_hostname}}'
    backrefs: yes
- name: replace server ip
  lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: 'Server=127.0.0.1'
    line: 'Server={{zabbix_server}}'
    backrefs: yes
- name: Make sure a service is running
  ansible.builtin.systemd:
    state: restarted
    enabled: yes
    name: zabbix-agent2
